### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by klardotsh** [MikeMorenoAudio/EP-MK1#1]
Hey there!

Loving this plugin and figured I'd try to package it up for the [Arch Linux AUR](https://aur.archlinux.org), but to "correctly" package it, I need to list a license - so far, I don't see any obvious hints at a license in the repo (looked for `COPYING`, `LICENSE`, etc. files as well as in a few README-esque files, came up empty-handed).

I'm assuming that, given this is on GitHub, an AUR package which simply pulls a tag from GitHub and compiles the plugin is OK, but I'd still like to properly set the license field on the resulting package if at all possible (if even only to appease the Arch Linux packaging standards).

Cheers!

**Comment by MikeMorenoDSP** [comment]
Hello 👋 

I'm glad you liked it. Thanks for letting me know about this issue.
[License.txt](https://github.com/MikeMorenoAudio/EP-MK1/blob/master/License.txt) is now uploaded.
I just specified the **"Standard Improved BSD License"** for the EP-MK1.

I hope this solves the issue. Thanks again! 👍
