### ISSUE TITLE
Use a standard license

### ISSUE THREAD

**Issue by kmturley** [MikeMorenoAudio/EP-MK1#13]
License file is here:
https://github.com/MikeMorenoDSP/EP-MK1/blob/master/License.txt

But GitHub detect as custom other license:
https://api.github.com/repos/MikeMorenoDSP/EP-MK1/license

This is problematic when using the GitHub API to categorize plugins by license type. Compare to a standard license API request:
https://api.github.com/repos/asb2m10/dexed/license

If you could use a standard license from either:
https://choosealicense.com/

OR the list here:
https://api.github.com/licenses

Would be much appreciated!

**Comment by MikeMorenoDSP** [comment]
Updated license to 3 claue BDS license from https://opensource.org/licenses/BSD-3-Clause
Did it work?

**Comment by kmturley** [comment]
Looks good to me:
```
"license": {
    "key": "bsd-3-clause",
    "name": "BSD 3-Clause \"New\" or \"Revised\" License",
    "spdx_id": "BSD-3-Clause",
    "url": "https://api.github.com/licenses/bsd-3-clause",
    "node_id": "MDc6TGljZW5zZTU="
}
```
https://api.github.com/repos/MikeMorenoDSP/EP-MK1/license

Thanks for the quick turnaround!
